### ISSUE TITLE
Use of uninitialized value $_ ... during global destruction

### ISSUE THREAD

**Issue by SpikesDivZero** [exodist/Child#12]
This fairly consistently shows up while running a full prove suite:

Use of uninitialized value $_ in numeric ne (!=) at Child.pm line 30 during global destruction.

**Comment by exodist** [comment]
@SpikesDivZero   would you please apply the patch listed above and see if it solves your issue?

**Comment by SpikesDivZero** [comment]
@exodist Looks to be working in my Vagrant box (running PE).

**Comment by exodist** [comment]
Interestingly release 12 fixes issue 12.

**Comment by SpikesDivZero** [comment]
Thanks, Chad!
